bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
   path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

suggestions/urls.py
from django.conf.urls import url
from .views import get_suggestions, suggestion_detail, create_or_edit_suggestion, upvotes

urlpatterns = [
    url(r'^suggestions', get_suggestions, name='get_suggestions'),
    url(r'^suggestions', suggestion_detail, name='suggestion_detail'),
    url(r'^new_suggestions', create_or_edit_suggestion, name='new_suggestion'),
    url(r'^(?P<pk>\d+)/edit/$', create_or_edit_suggestion, name='edit_suggestion'),
    url(r'^(?P<pk>\d+)/$', upvotes, name='upvotes'),
]

tech_buddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from news.views import get_posts
from suggestions import urls as urls_suggestions
from suggestions.views import get_suggestions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    url(r'^news/', get_posts, name='news'),
    url(r'^suggestions/', include('suggestions.urls')),
    url(r'^suggestions/', include(urls_suggestions)),
    url(r"^suggestions", get_suggestions, name="get_suggestions"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

suggestions/models.py
from django.db import models

"""
Suggestion Model below
"""
    
class Suggestion(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    upvotes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

suggestions/forms.py
from django import forms
from .models import Suggestion


class ProductSuggestForm(forms.ModelForm):

    class Meta:
        model = Suggestion
        fields = ('title', 'content')

suggestions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Suggestion
from .forms import ProductSuggestForm


def get_suggestions(request):
    paramsAsc = request.GET.get('asc_votes', '')
    paramsDsc = request.GET.get('dsc_votes', '')
    paramsOldest = request.GET.get('first_added', '')
    if paramsAsc:
            suggestions = Suggestion.objects.all().order_by('-upvotes')
    elif paramsDsc:   
            suggestions = Suggestion.objects.all().order_by('-upvotes').reverse()
    elif paramsOldest:   
            suggestions = Suggestion.objects.all()
    else:
        suggestions = Suggestion.objects.all().order_by('-id')
    
    return render(request, "suggestions.html", {'suggestions': suggestions})

asc_date=1

def suggestion_detail(request, pk):
    if request.method == "GET":
        suggestion = get_object_or_404(Suggestion, pk=pk)
        suggestion.save()
        return render(request, "suggestions.html", {'suggestion': suggestion})
    if request.method == "POST":
        suggestion = get_object_or_404(Suggestion, pk=pk)
        suggestion.upvotes += 1
        suggestion.save()
        return redirect('/suggestions/', {'suggestion': suggestion})


def create_or_edit_suggestion(request, pk=None):
    suggestion = get_object_or_404(Suggestion, pk=pk) if pk else None
    if request.method == "POST":
        form = ProductSuggestForm(request.POST, request.FILES, instance=suggestion)
        if form.is_valid():
            suggestion = form.save()
            return redirect('/suggestions/', {'suggestion': suggestion})
    else:
        form = ProductSuggestForm(instance=suggestion)
    return render(request, 'suggestionform.html', {'form': form})


def upvotes(request, pk):
    if request.method == "POST":
        upvotes = get_object_or_404(Suggestion, pk=pk)
        upvotes.upvotes += 1
        print(upvotes.upvotes)
        upvotes.save()
        return redirect('suggestions.html')

suggestions/templates/suggestion_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-sm-10 col-md-9">
            <h3>{{ suggestion.title }}</h3>
            <div class="row">
                <div class="col-xs-9">
                    <p>{{ suggestion.content }}</p>
                    <a href="{% url 'get_suggestions' %}" class="btn btn-default">Back to Suggestions</a>
                    <a href="{% url 'edit_suggestions' suggestion.id %}" class="btn btn-default">Edit Suggestion</a>
                    <hr>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

suggestions/templates/suggestionform.html
{% extends "base.html" %}

{% block content %}

<!-- Header  -->
<div class="jumbotron"> 
        <div class="container-fluid">
        </div> 
</div> 
<!--form for new products-->
      <div class="container mt-5 mb-5">
        <h2 class="logo-font text-center"> Add a new product Suggestion</h2>
         <hr style="height:2px;border-width:0;color:gray;background-color:black"> 
    <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
    <div id="div_id_title" class="form-group  ">
        <label for="id_title" class="control-label required-field ">
            Title
        </label>
        <div class="">
            <input type="text" name="title" maxlength="200" class=" form-control" required id="id_title" />   
        </div>    
    </div>
<div id="div_id_content" class="form-group  ">
    <label for="id_content" class="control-label required-field ">
          Content
    </label>
    <div class="">
        <textarea name="content" cols="40" rows="10" class=" form-control" required id="id_content"></textarea>
    </div>
</div>
        <button type="submit" class="btn btn-dark rounded-0">Add product suggestion</button>
    </form>
</div>

{% endblock %}

suggestions/templates/suggestions.html
{% extends 'base.html' %}

{% block content %}


<!-- Header  -->

<div class="jumbotron">
    <div class="container-fluid">
    </div>
</div>

<div class="container mb-5">
  <!-- Title  --> 
   <hr style="height:2px;border-width:0;color:gray;background-color:black"> 
        <div class="col text-center mt-3">
                <h2 class="logo-font"> Product Suggestions</h2>
        <p class="text-black">In this section you can make  any product suggestion . We will take  our customers feedback and we´ll do our best to add new products on sale based on your suggestions.</p>
    </div>
    <hr style="height:2px;border-width:0;color:gray;background-color:black">
     
    <!-- Suggestions filter dropdown -->
    <div class="container">
        <div class="row justify-content-end">
            <div class="dropdown mb-2">
                    <button class="btn btn-secondary rounded-0 btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filter Suggestions
            </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a name="asc_votes" href="?asc_votes=1" class="dropdown-item">Highest votes</a>
                        <a name="dsc_votes" href="?dsc_votes=1" class="dropdown-item">Lowest votes</a>
                        <a name="First_added" href="?first_added=1" class="dropdown-item">Oldest</a>
                        <a name="Last_added" href="?last_added=1" class="dropdown-item">Latest</a>
                    </div>
                </div>
            </div>
    </div>
    <!-- Suggestions  -->
    <div id="accordion">
        {% for suggestion in suggestions %}   
            <div class="card mb-3 rounded-0">
                <div class="card-header" id="headingOne">
                    <h5 class="mb-0 "> {{ suggestion.title }} </h5>
                        <!-- Upvotes  -->
                        <div class="float-right">
                            <form class="votes-form justify-content-end" method="post" action="{% url 'upvotes' suggestion.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn btn-dark rounded-0 btn-sm ">
                                            Votes <span class="badge badge-light">{{ suggestion.upvotes }}</span></button>
                            </form>
                            </div>
                        <!-- Upvotes  -->
                </div>
        
                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                    <div class="card-body">
                        {{ suggestion.content }}
                        
                    </div>
                </div>
            
            </div>
         {% endfor %}
    </div>


<!-- Button new suggestion  -->

    <a href="{% url 'new_suggestion' %}" class="btn btn-dark rounded-0 btn-sm btn-home-products" >Add Product Suggestion</a>

</div>
</div>
{% endblock %}